[package]
name = "fhe-ram"
version = "0.1.0"
edition = "2024"

[dependencies]
poulpy-hal = "0.3.1"
poulpy-core = "0.3.1"
poulpy-backend = "0.3.1"
poulpy-schemes = "0.3.0"
rand_core = "0.9.3"
itertools = "0.14.0"